import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = 'en' | 'hi' | 'bn' | 'te' | 'mr' | 'ta' | 'gu' | 'ur' | 'kn' | 'ml' | 'pa' | 'es' | 'fr' | 'de' | 'pt' | 'ar' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

// Translation dictionaries
const translations: Record<Language, Record<string, string>> = {
  en: {
    // App Name
    'app.name': 'AjnabiCam: Love Connects',
    'app.tagline': 'Where Every Connection Sparks a Story ✨',
    
    // Onboarding
    'onboarding.welcome': 'Welcome to AjnabiCam',
    'onboarding.subtitle': 'Set up your profile to get started',
    'onboarding.username': 'Username',
    'onboarding.username.placeholder': 'Enter your username',
    'onboarding.gender': 'Gender',
    'onboarding.gender.male': 'Male',
    'onboarding.gender.female': 'Female',
    'onboarding.language': 'Language',
    'onboarding.continue': 'Continue',
    'onboarding.skip': 'Skip for now',
    
    // Languages
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Español (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    
    // Home Screen
    'home.start': 'Find Your Match 💕',
    'home.features.hd': 'HD Video',
    'home.features.secure': 'Safe & Private',
    'home.features.instant': 'Instant Spark',
    
    // Navigation
    'nav.home': 'Home',
    'nav.chat': 'Chat',
    'nav.friends': 'Friends',
    'nav.voice': 'Voice',
    'nav.profile': 'Profile',
    
    // Profile Page
    'profile.title': 'Profile',
    'profile.premium.active': 'Premium Active',
    'profile.premium.enjoying': 'Enjoying all premium features! ✨',
    'profile.premium.upgrade': 'Upgrade to Premium',
    'profile.premium.unlock': 'Unlock exclusive features and enhanced experience!',
    'profile.premium.features.gender': '✓ Gender Filter',
    'profile.premium.features.voice': '✓ Voice Mode',
    'profile.premium.features.unlimited': '✓ Unlimited Time',
    'profile.username': 'Username',
    'profile.addPhoto': 'Add Photo',
    'profile.referral.title': 'Referral Rewards',
    'profile.referral.id': 'Your Referral ID',
    'profile.referral.copy': 'Copy',
    'profile.referral.reward': '🎁 Refer 1 friend successfully = 24h Premium FREE!',
    'profile.referral.share': 'Share your code and both you and your friend get premium benefits',
    'profile.settings': 'Settings',
    'profile.settings.privacy': 'Privacy Settings',
    'profile.settings.notifications': 'Notification Preferences',
    'profile.settings.account': 'Account Settings',
    'profile.settings.language': 'Language Settings',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.back': 'Back',
  },
  hi: {
    // App Name
    'app.name': 'अजनबीकैम',
    'app.tagline': 'अजनबियों से तुरंत जुड़ें',
    
    // Onboarding
    'onboarding.welcome': 'अजनबीकैम में आपका स्वागत है',
    'onboarding.subtitle': 'शुरू करने के लिए अपनी प्रोफ़ाइल सेट करें',
    'onboarding.username': 'उपयोगकर्ता नाम',
    'onboarding.username.placeholder': 'अपना उपयोगकर्ता नाम दर्ज ��रें',
    'onboarding.gender': 'लिंग',
    'onboarding.gender.male': 'पुरुष',
    'onboarding.gender.female': 'महिला',
    'onboarding.language': 'भाषा',
    'onboarding.continue': 'जारी रखें',
    'onboarding.skip': 'अभी छोड़ें',
    
    // Languages
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Español (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    
    // Home Screen
    'home.start': 'चैट शुरू करें',
    'home.features.hd': 'HD वीडियो',
    'home.features.secure': 'सुरक्षित',
    'home.features.instant': 'तुरंत',
    
    // Navigation
    'nav.home': 'होम',
    'nav.chat': 'चैट',
    'nav.friends': 'दोस्त',
    'nav.voice': 'आवाज़',
    'nav.profile': 'प्रोफ़ाइल',
    
    // Profile Page
    'profile.title': 'प्रोफ़ाइल',
    'profile.premium.active': 'प्रीमियम सक्रिय',
    'profile.premium.enjoying': 'सभी प्रीमियम सुविधाओं का आनंद ले रहे हैं! ✨',
    'profile.premium.upgrade': 'प्रीमियम में अपग्रेड करें',
    'profile.premium.unlock': 'विशेष सुविधाओं और बेहतर अनुभव को अनलॉक करें!',
    'profile.premium.features.gender': '✓ जेंडर फिल्टर',
    'profile.premium.features.voice': '✓ वॉयस मोड',
    'profile.premium.features.unlimited': '✓ असीमित समय',
    'profile.username': 'उपयोगकर्ता नाम',
    'profile.addPhoto': 'फोटो जोड़ें',
    'profile.referral.title': 'रेफरल रिवार्ड्स',
    'profile.referral.id': 'आपका रेफरल आईडी',
    'profile.referral.copy': 'कॉपी करें',
    'profile.referral.reward': '🎁 1 दोस्त को सफलतापूर्वक रेफर करें = 24 घंटे प्रीमियम मुफ्त!',
    'profile.referral.share': 'अपना कोड शेयर करें और आप और आपके दोस्त दोनों को प्रीमियम लाभ मिलें',
    'profile.settings': 'सेटिंग्स',
    'profile.settings.privacy': 'प्राइवेसी सेटिंग्स',
    'profile.settings.notifications': 'नोटिफिकेशन प्राथमिकताएं',
    'profile.settings.account': 'खाता सेटिंग्स',
    'profile.settings.language': 'भाषा सेटिंग्स',
    
    // Common
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.cancel': 'रद्द करें',
    'common.save': 'सेव करें',
    'common.back': 'वापस',
  },
  bn: {
    // App Name
    'app.name': 'আজনবীক্যাম',
    'app.tagline': 'অপরিচিতদের সাথে তাৎক্ষণিক সংযোগ',
    
    // Onboarding
    'onboarding.welcome': 'আজনবীক্যামে স্বাগতম',
    'onboarding.subtitle': 'শুরু করতে আপনার প্রোফাইল সেট করুন',
    'onboarding.username': 'ব্যবহারকারীর নাম',
    'onboarding.username.placeholder': 'আপনার ব্যবহারকারীর নাম লিখুন',
    'onboarding.gender': 'লিঙ্গ',
    'onboarding.gender.male': 'পুরুষ',
    'onboarding.gender.female': 'মহিলা',
    'onboarding.language': 'ভাষা',
    'onboarding.continue': 'অব্যাহত রাখুন',
    'onboarding.skip': 'এখনকার জন্য এড়িয়ে যান',
    
    // Languages - keeping all language names in their respective scripts
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Español (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    
    // Home Screen
    'home.start': 'চ্যাট শুরু করুন',
    'home.features.hd': 'HD ভিডিও',
    'home.features.secure': 'নিরাপদ',
    'home.features.instant': 'তাৎক্ষণিক',
    
    // Navigation
    'nav.home': 'হোম',
    'nav.chat': 'চ্যাট',
    'nav.friends': 'বন্ধুরা',
    'nav.voice': 'কণ্ঠস্বর',
    'nav.profile': 'প্রোফাইল',
    
    // Common
    'common.loading': 'লোড হচ্ছে...',
    'common.error': 'ত্রুটি',
    'common.success': 'সফল',
    'common.cancel': 'বাতিল',
    'common.save': 'সংরক্ষণ',
    'common.back': 'পিছনে',
  },
  te: {
    // Telugu translations
    'app.name': 'అజ్ఞాతక్యామ్',
    'app.tagline': 'అపరిచితులతో తక్షణ ��నెక్షన్',
    'onboarding.welcome': 'అజ్ఞాతక్యామ్‌కు స్వాగతం',
    'onboarding.subtitle': 'ప్రారంభించడానికి మీ ప్రొఫైల్‌ను సెట్ చేయండి',
    'onboarding.username': 'వినియోగదారు పేరు',
    'onboarding.username.placeholder': 'మీ వినియోగదారు పేరును నమోదు చేయండి',
    'onboarding.gender': 'లింగం',
    'onboarding.gender.male': 'పురుషుడు',
    'onboarding.gender.female': 'స్త్రీ',
    'onboarding.language': 'భాష',
    'onboarding.continue': 'కొనసాగించు',
    'onboarding.skip': 'ఇప్పుడు దాటవేయి',
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Español (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    'home.start': 'చాట్ ప్రారంభించండి',
    'nav.home': 'హోమ్',
    'nav.chat': 'చాట్',
    'nav.friends': 'స్నేహితులు',
    'nav.voice': 'వాయిస్',
    'nav.profile': 'ప్రొఫైల్',
    'common.loading': 'లోడ్ అవుతోంది...',
    'common.error': 'లోపం',
    'common.success': 'విజయం',
    'common.cancel': 'రద్దు చేయి',
    'common.save': 'సేవ్ చేయి',
    'common.back': 'వెనుకకు',
  },
  mr: {
    // Marathi translations
    'app.name': 'अजनबीकॅम',
    'app.tagline': 'अनोळखी लोकांशी तत्काळ कनेक्शन',
    'onboarding.welcome': 'अजनबीकॅममध्ये आपले स्वागत आहे',
    'onboarding.subtitle': 'सुरुवात करण्यासाठी आपली प्रोफाइल ��ेट करा',
    'onboarding.username': 'वापरकर्त्याचे नाव',
    'onboarding.username.placeholder': 'आपले वापरकर्त्याचे नाव प्रविष्ट करा',
    'onboarding.gender': 'लिंग',
    'onboarding.gender.male': 'पुरुष',
    'onboarding.gender.female': 'स्त्री',
    'onboarding.language': 'भाषा',
    'onboarding.continue': 'सुरू ठेवा',
    'onboarding.skip': 'आत्तासाठी वगळा',
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Español (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    'home.start': 'चॅट सुरू करा',
    'nav.home': 'होम',
    'nav.chat': 'चॅट',
    'nav.friends': 'मित्र',
    'nav.voice': 'आवाज',
    'nav.profile': 'प्रोफाइल',
    'common.loading': 'लोड होत आहे...',
    'common.error': 'त्रुटी',
    'common.success': 'यशस्वी',
    'common.cancel': 'रद्द करा',
    'common.save': 'सेव्ह करा',
    'common.back': 'मागे',
  },
  ta: {
    // Tamil translations
    'app.name': 'அஜ்னபிகாம்',
    'app.tagline': 'அறியாதவர்களுடன் உடனடி இணைப்பு',
    'onboarding.welcome': 'அஜ்னபிகாம்-க்கு வரவேற்கிறோம்',
    'onboarding.subtitle': 'தொடங்க உங்கள் சுயவிவரத்தை அமைக்கவும்',
    'onboarding.username': 'பயனர் பெயர்',
    'onboarding.username.placeholder': 'உங்கள் பயனர் பெயரை உள்ளிடவும்',
    'onboarding.gender': 'பாலினம்',
    'onboarding.gender.male': 'ஆண்',
    'onboarding.gender.female': 'பெண்',
    'onboarding.language': 'மொழி',
    'onboarding.continue': 'தொடரவும்',
    'onboarding.skip': 'இப்போது தவிர்க்கவும��',
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Español (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    'home.start': 'அரட்டையை தொடங்குங்கள்',
    'nav.home': 'வீடு',
    'nav.chat': 'அரட்டை',
    'nav.friends': 'நண்பர்கள்',
    'nav.voice': 'குரல்',
    'nav.profile': 'சுயவிவரம்',
    'common.loading': 'ஏற்றுகிறது...',
    'common.error': 'பிழை',
    'common.success': 'வெற்றி',
    'common.cancel': 'ரத்துச��ய்',
    'common.save': 'சேமி',
    'common.back': 'பின்னால்',
  },
  gu: {
    // Gujarati translations
    'app.name': 'અજનબીકૅમ',
    'app.tagline': 'અજાણ્યા લોકો સાથે તાત્કાલિક કનેક્શન',
    'onboarding.welcome': 'અજનબીકૅમમાં આપનું સ્વાગત છે',
    'onboarding.subtitle': 'શરૂ કરવા માટે તમારી પ્રોફાઇલ સેટ કરો',
    'onboarding.username': 'વપરાશકર્તા નામ',
    'onboarding.username.placeholder': 'તમારું વપરાશકર્તા નામ દાખલ કરો',
    'onboarding.gender': 'લિંગ',
    'onboarding.gender.male': 'પુરુષ',
    'onboarding.gender.female': 'સ્ત્રી',
    'onboarding.language': 'ભાષા',
    'onboarding.continue': 'ચાલુ રાખો',
    'onboarding.skip': 'હમણાં માટે છોડો',
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Español (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    'home.start': 'ચેટ શરૂ કરો',
    'nav.home': 'ઘર',
    'nav.chat': 'ચેટ',
    'nav.friends': 'મિત્રો',
    'nav.voice': 'અવાજ',
    'nav.profile': 'પ્રોફાઇલ',
    'common.loading': 'લોડ થઈ રહ્યું છે...',
    'common.error': 'ભૂલ',
    'common.success': 'સફળતા',
    'common.cancel': 'રદ કરો',
    'common.save': 'સેવ કરો',
    'common.back': 'પાછળ',
  },
  ur: {
    // Urdu translations
    'app.name': 'اجنبی کیم',
    'app.tagline': 'اجنبیوں سے فوری رابطہ',
    'onboarding.welcome': 'اجنبی کیم میں خوش آمدید',
    'onboarding.subtitle': 'شروع کرنے کے لیے اپنا پروفائل سیٹ کریں',
    'onboarding.username': 'صارف کا نام',
    'onboarding.username.placeholder': 'اپنا صارف نام درج کریں',
    'onboarding.gender': 'جنس',
    'onboarding.gender.male': 'مرد',
    'onboarding.gender.female': 'عورت',
    'onboarding.language': 'زبان',
    'onboarding.continue': 'جاری رکھیں',
    'onboarding.skip': 'ابھی چھوڑیں',
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Español (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    'home.start': 'چیٹ شروع کریں',
    'nav.home': 'ہوم',
    'nav.chat': 'چیٹ',
    'nav.friends': 'دوست',
    'nav.voice': 'آواز',
    'nav.profile': 'پروفائل',
    'common.loading': 'لوڈ ہو رہا ہے...',
    'common.error': 'خرابی',
    'common.success': 'کامیابی',
    'common.cancel': 'منسوخ کریں',
    'common.save': 'محفوظ کریں',
    'common.back': 'واپس',
  },
  kn: {
    // Kannada translations
    'app.name': 'ಅಜ್ಞಾತಕ್ಯಾಮ್',
    'app.tagline': 'ಅಪರಿಚಿತರೊಂದಿಗೆ ತಕ್ಷಣ ಸಂಪರ್ಕ',
    'onboarding.welcome': 'ಅಜ್ಞಾತಕ್ಯಾಮ್‌ಗೆ ಸ್ವಾಗತ',
    'onboarding.subtitle': 'ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಹೊಂದಿಸಿ',
    'onboarding.username': 'ಬಳಕೆದಾರ ಹೆಸರು',
    'onboarding.username.placeholder': 'ನಿಮ್ಮ ಬಳಕೆದಾರ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    'onboarding.gender': 'ಲಿಂಗ',
    'onboarding.gender.male': 'ಪುರುಷ',
    'onboarding.gender.female': 'ಮಹಿಳೆ',
    'onboarding.language': 'ಭಾಷೆ',
    'onboarding.continue': 'ಮುಂದುವರಿಸಿ',
    'onboarding.skip': 'ಈಗ ಬಿಟ್ಟುಬಿಡಿ',
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Español (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    'home.start': 'ಚಾಟ್ ಪ್ರಾರಂಭಿಸಿ',
    'nav.home': 'ಮನೆ',
    'nav.chat': 'ಚಾಟ್',
    'nav.friends': 'ಸ್ನೇಹಿತರು',
    'nav.voice': 'ಧ್ವನಿ',
    'nav.profile': 'ಪ್ರೊಫೈಲ್',
    'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'common.error': 'ದೋಷ',
    'common.success': 'ಯಶಸ್ಸು',
    'common.cancel': 'ರದ್ದುಗೊಳಿಸಿ',
    'common.save': 'ಉಳಿಸಿ',
    'common.back': 'ಹಿಂದೆ',
  },
  ml: {
    // Malayalam translations
    'app.name': 'അജ്ഞാതക്യാം',
    'app.tagline': 'അപരിചിതരുമായി തൽക്ഷണ കണക്ഷൻ',
    'onboarding.welcome': 'അജ്ഞാതക്യാമിലേക്ക് സ്വാഗതം',
    'onboarding.subtitle': 'ആരംഭിക്കാൻ നിങ്ങളുടെ പ്രൊഫൈൽ സജ്ജമാക്കുക',
    'onboarding.username': 'ഉപയോക്തൃനാമം',
    'onboarding.username.placeholder': 'നിങ്ങളുടെ ഉപയോക്തൃനാമം നൽകുക',
    'onboarding.gender': 'ലിംഗം',
    'onboarding.gender.male': 'പുരുഷൻ',
    'onboarding.gender.female': 'സ്ത്രീ',
    'onboarding.language': 'ഭാഷ',
    'onboarding.continue': 'തുടരുക',
    'onboarding.skip': 'ഇപ്പോൾ ഒഴിവാക്കുക',
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Español (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    'home.start': 'ചാറ്റ് ആരംഭിക്കുക',
    'nav.home': 'ഹോം',
    'nav.chat': 'ചാറ്റ്',
    'nav.friends': 'സുഹൃത്തുക്കൾ',
    'nav.voice': 'ശബ്ദം',
    'nav.profile': 'പ്രൊഫൈൽ',
    'common.loading': 'ലോഡുചെയ്യുന്നു...',
    'common.error': 'പിശക്',
    'common.success': 'വിജയം',
    'common.cancel': 'റദ്ദാക്കുക',
    'common.save': 'സംരക്ഷിക്കുക',
    'common.back': 'പിന്നോട്ട്',
  },
  pa: {
    // Punjabi translations
    'app.name': 'ਅਜਨਬੀਕੈਮ',
    'app.tagline': 'ਅਜਨਬੀਆਂ ਨਾਲ ਤੁਰੰਤ ਕਨੈਕਸ਼ਨ',
    'onboarding.welcome': 'ਅਜਨਬੀਕੈਮ ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ',
    'onboarding.subtitle': 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਆਪਣਾ ਪ੍ਰੋਫਾਈਲ ਸੈੱਟ ਕਰੋ',
    'onboarding.username': 'ਯੂਜ਼ਰ ਨਾਮ',
    'onboarding.username.placeholder': 'ਆਪਣਾ ਯੂਜ਼ਰ ਨਾਮ ਦਾਖਲ ਕਰੋ',
    'onboarding.gender': 'ਲਿੰਗ',
    'onboarding.gender.male': 'ਮਰਦ',
    'onboarding.gender.female': 'ਔਰਤ',
    'onboarding.language': 'ਭਾਸ਼ਾ',
    'onboarding.continue': 'ਜਾਰੀ ਰੱਖੋ',
    'onboarding.skip': 'ਹੁਣ ਛੱਡੋ',
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Español (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    'home.start': 'ਚੈਟ ਸ਼ੁਰੂ ਕਰੋ',
    'nav.home': 'ਘਰ',
    'nav.chat': 'ਚੈਟ',
    'nav.friends': 'ਦੋਸਤ',
    'nav.voice': 'ਆਵਾਜ਼',
    'nav.profile': 'ਪ੍ਰੋਫਾਈਲ',
    'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    'common.error': 'ਗਲਤੀ',
    'common.success': 'ਸਫਲਤਾ',
    'common.cancel': 'ਰੱਦ ਕਰੋ',
    'common.save': 'ਸੇਵ ਕਰੋ',
    'common.back': 'ਵਾਪਸ',
  },
  // Keep existing translations for non-Indian languages
  es: {
    'app.name': 'AjnabiCam',
    'app.tagline': 'Conecta con extraños al instante',
    'onboarding.welcome': 'Bienvenido a AjnabiCam',
    'onboarding.subtitle': 'Configura tu perfil para comenzar',
    'onboarding.username': 'Nombre de usuario',
    'onboarding.username.placeholder': 'Ingresa tu nombre de usuario',
    'onboarding.gender': 'Género',
    'onboarding.gender.male': 'Masculino',
    'onboarding.gender.female': 'Femenino',
    'onboarding.language': 'Idioma',
    'onboarding.continue': 'Continuar',
    'onboarding.skip': 'Omitir por ahora',
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Español (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    'home.start': 'Comenzar a chatear',
    'nav.home': 'Inicio',
    'nav.chat': 'Chat',
    'nav.friends': 'Amigos',
    'nav.voice': 'Voz',
    'nav.profile': 'Perfil',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.back': 'Atrás',
  },
  fr: {
    'app.name': 'AjnabiCam',
    'app.tagline': 'Connectez-vous instantanément avec des inconnus',
    'onboarding.welcome': 'Bienvenue sur AjnabiCam',
    'onboarding.subtitle': 'Configurez votre profil pour commencer',
    'onboarding.username': "Nom d'utilisateur",
    'onboarding.username.placeholder': "Entrez votre nom d'utilisateur",
    'onboarding.gender': 'Genre',
    'onboarding.gender.male': 'Masculin',
    'onboarding.gender.female': 'Féminin',
    'onboarding.language': 'Langue',
    'onboarding.continue': 'Continuer',
    'onboarding.skip': 'Passer pour maintenant',
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Español (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    'home.start': 'Commencer à chatter',
    'nav.home': 'Accueil',
    'nav.chat': 'Chat',
    'nav.friends': 'Amis',
    'nav.voice': 'Voix',
    'nav.profile': 'Profil',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.save': 'Sauvegarder',
    'common.back': 'Retour',
  },
  de: {
    'app.name': 'AjnabiCam',
    'app.tagline': 'Verbinde dich sofort mit Fremden',
    'onboarding.welcome': 'Willkommen bei AjnabiCam',
    'onboarding.subtitle': 'Richte dein Profil ein, um zu beginnen',
    'onboarding.username': 'Benutzername',
    'onboarding.username.placeholder': 'Gib deinen Benutzernamen ein',
    'onboarding.gender': 'Geschlecht',
    'onboarding.gender.male': 'Männlich',
    'onboarding.gender.female': 'Weiblich',
    'onboarding.language': 'Sprache',
    'onboarding.continue': 'Weiter',
    'onboarding.skip': 'Vorerst überspringen',
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Espa��ol (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    'home.start': 'Chat starten',
    'nav.home': 'Startseite',
    'nav.chat': 'Chat',
    'nav.friends': 'Freunde',
    'nav.voice': 'Stimme',
    'nav.profile': 'Profil',
    'common.loading': 'Lädt...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.back': 'Zurück',
  },
  pt: {
    'app.name': 'AjnabiCam',
    'app.tagline': 'Conecte-se instantaneamente com estranhos',
    'onboarding.welcome': 'Bem-vindo ao AjnabiCam',
    'onboarding.subtitle': 'Configure seu perfil para começar',
    'onboarding.username': 'Nome de usuário',
    'onboarding.username.placeholder': 'Digite seu nome de usuário',
    'onboarding.gender': 'Gênero',
    'onboarding.gender.male': 'Masculino',
    'onboarding.gender.female': 'Feminino',
    'onboarding.language': 'Idioma',
    'onboarding.continue': 'Continuar',
    'onboarding.skip': 'Pular por agora',
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Español (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    'home.start': 'Começar a conversar',
    'nav.home': 'Início',
    'nav.chat': 'Chat',
    'nav.friends': 'Amigos',
    'nav.voice': 'Voz',
    'nav.profile': 'Perfil',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.back': 'Voltar',
  },
  ar: {
    'app.name': 'أجنبي كام',
    'app.tagline': 'تواصل مع الغرباء فوراً',
    'onboarding.welcome': 'مرحباً بك في أجنبي كام',
    'onboarding.subtitle': 'ق�� بإعداد ملفك الشخصي للبدء',
    'onboarding.username': 'اسم المستخدم',
    'onboarding.username.placeholder': 'أدخل اسم المستخدم',
    'onboarding.gender': 'الجنس',
    'onboarding.gender.male': 'ذكر',
    'onboarding.gender.female': 'أنثى',
    'onboarding.language': 'اللغة',
    'onboarding.continue': 'متابعة',
    'onboarding.skip': 'تخطي الآن',
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Español (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    'home.start': 'بدء المحادثة',
    'nav.home': 'الرئيسية',
    'nav.chat': 'المحادثة',
    'nav.friends': 'الأصدقاء',
    'nav.voice': 'الصوت',
    'nav.profile': 'الملف الشخصي',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.back': 'رجوع',
  },
  zh: {
    'app.name': '陌生人摄像头',
    'app.tagline': '立即与陌生人连接',
    'onboarding.welcome': '欢迎来到陌生人摄像头',
    'onboarding.subtitle': '设置您的个人资料以开始',
    'onboarding.username': '用户名',
    'onboarding.username.placeholder': '输入您的用户名',
    'onboarding.gender': '性别',
    'onboarding.gender.male': '男性',
    'onboarding.gender.female': '女性',
    'onboarding.language': '语言',
    'onboarding.continue': '继续',
    'onboarding.skip': '暂时跳过',
    'language.english': 'English',
    'language.hindi': 'हिंदी (Hindi)',
    'language.bengali': 'বাংলা (Bengali)',
    'language.telugu': 'తెలుగు (Telugu)',
    'language.marathi': 'मराठी (Marathi)',
    'language.tamil': 'தமிழ் (Tamil)',
    'language.gujarati': 'ગુજરાતી (Gujarati)',
    'language.urdu': 'اردو (Urdu)',
    'language.kannada': 'ಕನ್ನಡ (Kannada)',
    'language.malayalam': 'മലയാളം (Malayalam)',
    'language.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    'language.spanish': 'Español (Spanish)',
    'language.french': 'Français (French)',
    'language.german': 'Deutsch (German)',
    'language.portuguese': 'Português (Portuguese)',
    'language.arabic': 'العربية (Arabic)',
    'language.chinese': '中文 (Chinese)',
    'home.start': '开始聊天',
    'nav.home': '首页',
    'nav.chat': '聊天',
    'nav.friends': '朋友',
    'nav.voice': '语音',
    'nav.profile': '个人资料',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.back': '返回',
  },
};

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<Language>('en');

  // Load saved language on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('ajnabicam_language') as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('ajnabicam_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const languages: Array<{ code: Language; name: string; flag: string }> = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'hi', name: 'हिंदी', flag: '🇮🇳' },
  { code: 'bn', name: 'বাংলা', flag: '🇧🇩' },
  { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
  { code: 'mr', name: 'मराठी', flag: '🇮🇳' },
  { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' },
  { code: 'gu', name: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'ur', name: 'اردو', flag: '🇵🇰' },
  { code: 'kn', name: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'മലയാളം', flag: '🇮🇳' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'pt', name: 'Português', flag: '🇧🇷' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
];
